---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.rameshwarkanade.online
  resources:
  - wordpresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.rameshwarkanade.online
  resources:
  - wordpresses/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.rameshwarkanade.online
  resources:
  - wordpresses/status
  verbs:
  - get
  - patch
  - update
